import asyncio
import re
import time
from collections.abc import AsyncIterator, Callable, Iterator
from concurrent.futures import ThreadPoolExecutor

import pytest
from fastapi.testclient import TestClient
from openai import APIConnectionError
from openai.types.chat import ChatCompletionMessageParam

from simplechat.config import Settings
from simplechat.llm import ChunkKind, ThinkingOptions
from simplechat.main import create_app
from simplechat.store import Conversation, Store

SETTINGS = Settings(
    ollama_url="http://unused",
    ollama_api_key="unused",
    default_model="",
    host="127.0.0.1",
    port=8000,
)

# llama3 cannot think; qwen3 can.
QWEN_THINKING = ThinkingOptions(levels=["none", "low", "high"], default="high")


class FakeBackend:
    def __init__(
        self, chunks: list[tuple[ChunkKind, str]] | None = None, fail: bool = False
    ) -> None:
        self.chunks = chunks or [
            ("content", "Hello"),
            ("content", ", <world>"),
            ("content", "!\nBye"),
        ]
        self.fail = fail
        # Set to False to hold replies in the "streaming" state until set back to True.
        self.released = True
        self.calls: list[tuple[str, list[ChatCompletionMessageParam], str]] = []

    async def list_models(self) -> list[str]:
        return ["llama3", "qwen3"]

    async def thinking_options(self, model: str) -> ThinkingOptions | None:
        return QWEN_THINKING if model == "qwen3" else None

    async def stream_chat(
        self, model: str, messages: list[ChatCompletionMessageParam], thinking: str = ""
    ) -> AsyncIterator[tuple[ChunkKind, str]]:
        self.calls.append((model, messages, thinking))
        if self.fail:
            raise APIConnectionError(request=None)  # type: ignore[arg-type]
        while not self.released:
            await asyncio.sleep(0.005)
        for chunk in self.chunks:
            yield chunk


@pytest.fixture
def backend() -> FakeBackend:
    return FakeBackend()


@pytest.fixture
def store() -> Store:
    return Store()


@pytest.fixture
def client(backend: FakeBackend, store: Store) -> Iterator[TestClient]:
    # Used as a context manager so one event loop runs across requests; replies are
    # generated by background tasks on that loop.
    with TestClient(create_app(settings=SETTINGS, backend=backend, store=store)) as client:
        yield client


@pytest.fixture
def conversation(client: TestClient, store: Store) -> Conversation:
    client.post("/c")
    return store.recent()[0]


def stream(client: TestClient, conversation: Conversation, message_id: str) -> str:
    """Wait for a reply to finish and return its SSE stream."""
    return client.get(f"/c/{conversation.id}/stream/{message_id}").text


def concurrently[T](backend: FakeBackend, *calls: Callable[[], T]) -> list[T]:
    """Run requests at the same time while the backend holds replies, then release it.

    Replies are generated in the background, so a stream opened after a reply
    finished only gets `done`. Holding the backend lets requests attach first.
    """
    with ThreadPoolExecutor(max_workers=len(calls)) as pool:
        futures = [pool.submit(call) for call in calls]
        time.sleep(0.1)  # let the requests reach the app
        backend.released = True
        return [future.result(timeout=5) for future in futures]


def test_index_creates_conversation_with_first_model(client: TestClient, store: Store) -> None:
    response = client.get("/", follow_redirects=False)
    assert response.status_code == 303
    (conversation,) = store.recent()
    assert response.headers["location"] == f"/c/{conversation.id}"
    assert conversation.model == "llama3"


def test_chat_page_renders(client: TestClient, conversation: Conversation) -> None:
    response = client.get(f"/c/{conversation.id}")
    assert response.status_code == 200
    assert '<option value="qwen3">qwen3</option>' in response.text


def test_unknown_conversation_is_404(client: TestClient) -> None:
    assert client.get("/c/nope").status_code == 404


def test_send_and_stream(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    conversation.system_prompt = "Be brief."
    backend.released = False
    response = client.post(f"/c/{conversation.id}/messages", data={"content": "Hi <b>"})
    assert response.status_code == 200
    assert "Hi &lt;b&gt;" in response.text
    assert 'sse-connect="/c/' in response.text
    assert 'hx-swap-oob="true"' in response.text

    reply = conversation.active_path()[1]
    [body] = concurrently(backend, lambda: stream(client, conversation, reply.id))

    assert "event: content\ndata: , &lt;world&gt;" in body
    # A newline inside a chunk becomes two data lines, which the browser joins with "\n".
    assert "data: !\ndata: Bye" in body
    assert "event: done" in body
    assert reply.content == "Hello, <world>!\nBye"
    assert reply.status == "done"
    assert backend.calls == [
        (
            "llama3",
            [
                {"role": "system", "content": "Be brief."},
                {"role": "user", "content": "Hi <b>"},
            ],
            "",
        )
    ]


def test_thinking_is_streamed_and_kept_out_of_history(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    backend.chunks = [("thinking", "Hmm <ok>"), ("content", "Answer")]
    backend.released = False
    client.post(f"/c/{conversation.id}/messages", data={"content": "Q1"})
    reply = conversation.active_path()[1]
    [body] = concurrently(backend, lambda: stream(client, conversation, reply.id))

    assert "event: thinking\ndata: Hmm &lt;ok&gt;" in body
    assert reply.thinking == "Hmm <ok>"
    assert reply.content == "Answer"
    # The finished message shows the thoughts collapsed.
    assert '<details class="thinking">' in body
    assert "Thoughts" in body

    client.post(f"/c/{conversation.id}/messages", data={"content": "Q2"})
    stream(client, conversation, conversation.active_path()[-1].id)
    _, history, _ = backend.calls[-1]
    assert history[1] == {"role": "assistant", "content": "Answer"}


def test_thinking_picker_follows_model(client: TestClient, conversation: Conversation) -> None:
    page = client.get(f"/c/{conversation.id}")
    assert 'id="thinking-select" aria-label="Thinking level" hidden' in page.text

    response = client.post(
        f"/c/{conversation.id}/settings", data={"model": "qwen3", "thinking": "none"}
    )
    assert response.status_code == 200
    assert "Thinking: default (high)" in response.text
    assert '<option value="none" selected>Thinking: off</option>' in response.text
    assert conversation.thinking == "none"

    # llama3 cannot think, so the level resets and the picker hides.
    response = client.post(
        f"/c/{conversation.id}/settings", data={"model": "llama3", "thinking": "none"}
    )
    assert conversation.thinking == ""
    assert "hidden" in response.text


def test_thinking_level_is_sent(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    client.post(f"/c/{conversation.id}/settings", data={"model": "qwen3", "thinking": "low"})
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    stream(client, conversation, conversation.active_path()[1].id)
    assert backend.calls[-1][0] == "qwen3"
    assert backend.calls[-1][2] == "low"


def test_stream_twice_does_not_regenerate(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    reply = conversation.active_path()[1]
    stream(client, conversation, reply.id)
    body = stream(client, conversation, reply.id)
    assert "event: content" not in body
    assert "event: done" in body
    assert len(backend.calls) == 1


def test_stream_error_is_shown(client: TestClient, store: Store) -> None:
    client.app.state.backend = FakeBackend(fail=True)  # type: ignore[attr-defined]
    client.post("/c")
    conversation = store.recent()[0]
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    reply = conversation.active_path()[1]
    body = stream(client, conversation, reply.id)
    assert reply.status == "error"
    assert "Connection error" in body
    assert "Retry" in body


def test_send_while_busy_is_409(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    backend.released = False
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    response = client.post(f"/c/{conversation.id}/messages", data={"content": "Again"})
    backend.released = True
    assert response.status_code == 409


def test_concurrent_sends_start_one_turn(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    backend.released = False
    send = lambda: client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})  # noqa: E731
    responses = concurrently(backend, send, send, send)
    assert sorted(r.status_code for r in responses) == [200, 409, 409]
    assert len(conversation.active_path()) == 2


def test_reconnecting_clients_follow_the_same_generation(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    backend.released = False
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    reply = conversation.active_path()[1]
    follow = lambda: stream(client, conversation, reply.id)  # noqa: E731
    bodies = concurrently(backend, follow, follow)

    for body in bodies:
        # Each client gets every chunk, then `done` with the finished message,
        # not a busy one that would reconnect again.
        assert body.count("event: content") == 3
        assert 'class="msg assistant done"' in body.split("event: done", 1)[1]
    assert len(backend.calls) == 1


def test_generation_finishes_without_a_client(
    client: TestClient, conversation: Conversation
) -> None:
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    reply = conversation.active_path()[1]
    deadline = time.monotonic() + 5
    while reply.is_busy and time.monotonic() < deadline:
        time.sleep(0.01)
    assert reply.status == "done"
    assert reply.content == "Hello, <world>!\nBye"


def test_busy_reply_renders_empty(
    client: TestClient, conversation: Conversation, backend: FakeBackend
) -> None:
    backend.released = False
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    # Its stream replays every chunk, so a reload must not show partial text too.
    conversation.active_path()[1].content = "partial"
    page = client.get(f"/c/{conversation.id}")
    backend.released = True
    assert "partial" not in page.text
    assert 'sse-connect="/c/' in page.text


def test_empty_message_is_rejected(client: TestClient, conversation: Conversation) -> None:
    response = client.post(f"/c/{conversation.id}/messages", data={"content": "   "})
    assert response.status_code == 422


def test_edit_regenerate_and_switch(client: TestClient, conversation: Conversation) -> None:
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    user, reply = conversation.active_path()
    stream(client, conversation, reply.id)
    base = f"/c/{conversation.id}/messages"

    form = client.get(f"{base}/{user.id}/edit")
    assert "<textarea" in form.text

    response = client.post(f"{base}/{user.id}/edit", data={"content": "Hello"})
    assert response.status_code == 200
    assert "1 / 2" not in response.text
    assert "2 / 2" in response.text
    new_user, new_reply = conversation.active_path()
    assert new_user.content == "Hello"
    stream(client, conversation, new_reply.id)

    response = client.post(f"{base}/{new_reply.id}/regenerate")
    assert response.status_code == 200
    newest_reply = conversation.active_path()[1]
    assert newest_reply.status == "pending"
    stream(client, conversation, newest_reply.id)

    response = client.post(f"{base}/{new_user.id}/switch", data={"step": "-1"})
    assert response.status_code == 200
    assert [m.content for m in conversation.active_path()] == ["Hi", reply.content]
    assert re.search(r">\s*1 / 2\s*<", response.text)


def test_regenerate_user_message_is_400(client: TestClient, conversation: Conversation) -> None:
    client.post(f"/c/{conversation.id}/messages", data={"content": "Hi"})
    user, reply = conversation.active_path()
    stream(client, conversation, reply.id)
    response = client.post(f"/c/{conversation.id}/messages/{user.id}/regenerate")
    assert response.status_code == 400


def test_update_settings(client: TestClient, conversation: Conversation) -> None:
    response = client.post(
        f"/c/{conversation.id}/settings",
        data={"model": "qwen3", "system_prompt": "Answer in Japanese."},
    )
    assert response.status_code == 200
    assert conversation.model == "qwen3"
    assert conversation.system_prompt == "Answer in Japanese."


def test_delete_current_redirects(
    client: TestClient, conversation: Conversation, store: Store
) -> None:
    response = client.delete(f"/c/{conversation.id}", params={"current": conversation.id})
    assert response.headers["HX-Redirect"] == "/"
    assert store.get(conversation.id) is None


def test_delete_other_returns_sidebar(client: TestClient, store: Store) -> None:
    client.post("/c")
    client.post("/c")
    current, other = store.recent()
    response = client.delete(f"/c/{other.id}", params={"current": current.id})
    assert 'id="conversation-list"' in response.text
    assert other.id not in response.text
